[[CURRENCIES]]
code = "MIB"
issuer = "GDUD6OAXBWXCIEOJ4RB5Q4ABN3L757I3M3NKERPSECCENYVXJN6NCSR3"
name = "Mediceberg Token"
desc = "A Testnet token created by Mediciberg for Pi Network experimentation Official Test Token for HIB community on PI Testnet. Total supply: 1000000 MIB"
image = https:// "mediceberg-token.netlify.app/stellar-assets/mib-logo.jpg"
orgName = "Mediceberg Project"
orgURL = "https://Mediceberg.github.io"
